In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=0)
category = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=1)
employees = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=2)
employee_territories = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=3)
order_details = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=4)
orders = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=5)
shippers = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=6)
suppliers = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=7)
products = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=8)
regions = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=9)
territories = pd.read_excel("Northwind_Project_full.xlsx", sheet_name=10)

In [3]:
products = products[:77]
products["Discontinued"] = products["Discontinued"].astype(int)
products["CategoryID"] = products["CategoryID"].astype(int)
products["TotalUnits"] = products["UnitsOnOrder"] + products["UnitsInStock"]
products["TotalCost"] = products["TotalUnits"] * products["UnitPrice"]
products_name = products[["CategoryID", "ProductName", "UnitPrice", "TotalUnits", "TotalCost", "Discontinued"]]
products_name

,CategoryID,ProductName,UnitPrice,TotalUnits,TotalCost,Discontinued
0,6,Alice Mutton,19.500,0,0.000,1
1,2,Aniseed Syrup,5.000,83,415.000,0
2,8,Boston Crab Meat,9.200,123,1131.600,0
3,4,Camembert Pierrot,17.000,19,323.000,0
4,8,Carnarvon Tigers,31.250,42,1312.500,0
...,...,...,...,...,...,...
72,7,Uncle Bob's Organic Dried Pears,15.000,15,225.000,0
73,3,Valkoinen suklaa,8.125,65,528.125,0
74,2,Vegie-spread,21.950,24,526.800,0
75,5,Wimmers gute Semmelknצdel,16.625,102,1695.750,0
76,3,Zaanse koeken,4.750,36,171.000,0

In [4]:
orders_and_details = pd.merge(order_details, orders)
orders_and_details.head()

,OrderID,ProductID,UnitPrice,Quantity,Discount,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry
0,10248,11,14.0,12,0.0,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10248,42,9.8,10,0.0,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
2,10248,72,34.8,5,0.0,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
3,10249,14,18.6,9,0.0,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitהten,Luisenstr. 48,Mnster,NaN,44087,Germany
4,10249,51,42.4,40,0.0,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitהten,Luisenstr. 48,Mnster,NaN,44087,Germany

In [5]:
details_name = pd.merge(order_details, products[["ProductID", "ProductName"]], on="ProductID", how="left")
details_name["TotalPrice"] = (details_name["UnitPrice"] * details_name["Quantity"]) * (1 - details_name["Discount"])
details_name

,OrderID,ProductID,UnitPrice,Quantity,Discount,ProductName,TotalPrice
0,10248,11,14.00,12,0.00,Queso Cabrales,168.000
1,10248,42,9.80,10,0.00,Singaporean Hokkien Fried Mee,98.000
2,10248,72,34.80,5,0.00,Mozzarella di Giovanni,174.000
3,10249,14,18.60,9,0.00,Tofu,167.400
4,10249,51,42.40,40,0.00,Manjimup Dried Apples,1696.000
...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,Wimmers gute Semmelknצdel,64.505
2151,11077,66,17.00,1,0.00,Louisiana Hot Spiced Okra,17.000
2152,11077,73,15.00,2,0.01,Rצd Kaviar,29.700
2153,11077,75,7.75,4,0.00,Rhצnbrהu Klosterbier,31.000
2154,11077,77,13.00,2,0.00,Original Frankfurter grne Soe,26.000

In [6]:
group_details_name = details_name.groupby(["ProductName"])[["TotalPrice"]].sum().reset_index()
group_details_name

                        ProductName  TotalPrice
0                      Alice Mutton  32698.3800
1                     Aniseed Syrup   3044.0000
2                  Boston Crab Meat  17910.6300
3                 Camembert Pierrot  46825.4800
4                  Carnarvon Tigers  29171.8750
..                              ...         ...
72  Uncle Bob's Organic Dried Pears  22044.3000
73                 Valkoinen suklaa   3437.6875
74                     Vegie-spread  16701.0950
75        Wimmers gute Semmelknצdel  21957.9675
76                    Zaanse koeken   3958.0800

[77 rows x 2 columns]

In [7]:
profits = pd.merge(group_details_name, products_name)
profits["Profit"] = profits["TotalPrice"] - profits["TotalCost"]
profits

,ProductName,TotalPrice,CategoryID,UnitPrice,TotalUnits,TotalCost,Discontinued,Profit
0,Alice Mutton,32698.3800,6,19.500,0,0.000,1,32698.3800
1,Aniseed Syrup,3044.0000,2,5.000,83,415.000,0,2629.0000
2,Boston Crab Meat,17910.6300,8,9.200,123,1131.600,0,16779.0300
3,Camembert Pierrot,46825.4800,4,17.000,19,323.000,0,46502.4800
4,Carnarvon Tigers,29171.8750,8,31.250,42,1312.500,0,27859.3750
...,...,...,...,...,...,...,...,...
72,Uncle Bob's Organic Dried Pears,22044.3000,7,15.000,15,225.000,0,21819.3000
73,Valkoinen suklaa,3437.6875,3,8.125,65,528.125,0,2909.5625
74,Vegie-spread,16701.0950,2,21.950,24,526.800,0,16174.2950
75,Wimmers gute Semmelknצdel,21957.9675,5,16.625,102,1695.750,0,20262.2175
76,Zaanse koeken,3958.0800,3,4.750,36,171.000,0,3787.0800

In [8]:
profit_category = pd.merge(profits, category[["CategoryID", "CategoryName"]])
profit_category

,ProductName,TotalPrice,CategoryID,UnitPrice,TotalUnits,TotalCost,Discontinued,Profit,CategoryName
0,Alice Mutton,32698.3800,6,19.500,0,0.000,1,32698.3800,Meat/Poultry
1,Aniseed Syrup,3044.0000,2,5.000,83,415.000,0,2629.0000,Condiments
2,Boston Crab Meat,17910.6300,8,9.200,123,1131.600,0,16779.0300,Seafood
3,Camembert Pierrot,46825.4800,4,17.000,19,323.000,0,46502.4800,Dairy Products
4,Carnarvon Tigers,29171.8750,8,31.250,42,1312.500,0,27859.3750,Seafood
...,...,...,...,...,...,...,...,...,...
72,Uncle Bob's Organic Dried Pears,22044.3000,7,15.000,15,225.000,0,21819.3000,Produce
73,Valkoinen suklaa,3437.6875,3,8.125,65,528.125,0,2909.5625,Confections
74,Vegie-spread,16701.0950,2,21.950,24,526.800,0,16174.2950,Condiments
75,Wimmers gute Semmelknצdel,21957.9675,5,16.625,102,1695.750,0,20262.2175,Grains/Cereals
76,Zaanse koeken,3958.0800,3,4.750,36,171.000,0,3787.0800,Confections

In [9]:
profit_category.to_excel('profit_category.xlsx', index=False)

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

le = LabelEncoder()
profit_category['Category_Encoded'] = le.fit_transform(profit_category['CategoryName'])

features = ['UnitPrice', 'TotalUnits', 'TotalCost', 'Category_Encoded']
X = profit_category[features]
y = profit_category['Discontinued']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier(n_estimators=1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print(classification_report(y_test, y_pred))

Accuracy: 0.88
              precision    recall  f1-score   support

           0       0.92      0.92      0.92        13
           1       0.67      0.67      0.67         3

    accuracy                           0.88        16
   macro avg       0.79      0.79      0.79        16
weighted avg       0.88      0.88      0.88        16